name: Unzip and Commit

on:
  workflow_dispatch:
  push:
    paths:
      - '*.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Unzip files
        run: |
          mkdir unzipped_content
          unzip '*.zip' -d unzipped_content

      - name: Commit unzipped content
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add unzipped_content
          git commit -m "Add unzipped content"
          git push